Configure build timeout in Jenkins
screwdriver-cd/executor-jenkins pull request #22
Opened 2018-07-25 07:46 UTC by aty55

## Context
This PR implements that users can configure build timeout in Jenkins.

## Objective
Use the annotation for users to configure their own build timeouts in Jenkins.
As below...
```
annotations:
      beta.screwdriver.cd/executor: jenkins
      beta.screwdriver.cd/timeout: 30
```

## References
screwdriver-cd/screwdriver PR:

2018-07-25 07:46 UTC, yahoocla commented
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

2018-07-25 20:48 UTC, Filbird requested changes

2018-07-25 20:48 UTC, Filbird commented on index.js
> +        this.buildTimeout = options.jenkins.buildTimet || 90;
buildTimeout*

2018-07-26 01:28 UTC, att55 commented on index.js
> +        this.buildTimeout = options.jenkins.buildTimet || 90;
Corrected 🙇

2018-07-27 00:19 UTC, tkyi approved these changes
LGTM 👍

2018-07-27 16:51 UTC, jithine approved these changes

2018-07-27 18:19 UTC, merged